pub mod handlers;
pub mod routes;

pub const BACKEND_API_PREFIX: &str = "/backend/v3/api";

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HttpMethod {
    Delete,
    Get,
    Patch,
    Post,
    Put,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NewsHttpRoute {
    pub method: HttpMethod,
    pub path: &'static str,
    pub tag: &'static str,
    pub operation_id: &'static str,
}

impl NewsHttpRoute {
    pub const fn new(
        method: HttpMethod,
        path: &'static str,
        tag: &'static str,
        operation_id: &'static str,
    ) -> Self {
        Self {
            method,
            path,
            tag,
            operation_id,
        }
    }
}

pub fn backend_routes() -> Vec<NewsHttpRoute> {
    vec![
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/categories",
            "categories.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/categories",
            "categories.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/categories/{categoryId}",
            "categories.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/categories/{categoryId}",
            "categories.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/items",
            "items.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items",
            "items.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/items/{itemId}",
            "items.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/items/{itemId}",
            "items.delete",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/{itemId}/publish",
            "items.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/{itemId}/schedule",
            "items.schedule",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/{itemId}/archive",
            "items.archive",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/{itemId}/feature",
            "items.feature",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/items/{itemId}/editorial_readiness",
            "items.editorialReadiness.retrieve",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/sources",
            "sources.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/sources",
            "sources.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/sources/{sourceId}",
            "sources.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/sources/{sourceId}",
            "sources.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/authors",
            "authors.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/authors",
            "authors.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/authors/{authorId}",
            "authors.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/authors/{authorId}",
            "authors.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/channels",
            "channels.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/channels",
            "channels.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/channels/{channelId}",
            "channels.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/channels/{channelId}",
            "channels.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/topics",
            "topics.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/topics",
            "topics.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/topics/{topicId}",
            "topics.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/topics/{topicId}",
            "topics.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/items/{itemId}/versions",
            "items.versions.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/{itemId}/versions",
            "items.versions.create",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/items/{itemId}/media",
            "items.media.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/{itemId}/media",
            "items.media.create",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/items/{itemId}/media/{mediaId}",
            "items.media.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/moderation/cases",
            "moderation.cases.list",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/moderation/cases/{caseId}",
            "moderation.cases.retrieve",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/moderation/cases/{caseId}",
            "moderation.cases.update",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/comments/moderation",
            "comments.moderation.list",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/comments/{commentId}/moderation",
            "comments.moderation.update",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/reports",
            "reports.management.list",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/reports/{reportId}",
            "reports.update",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/trending/metrics",
            "trending.metrics.list",
        ),
        route(
            HttpMethod::Put,
            "/backend/v3/api/news/trending/metrics",
            "trending.metrics.update",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/items/metrics",
            "items.metrics.list",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/items/{itemId}/metrics",
            "items.metrics.retrieve",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/items/metrics/rebuild",
            "items.metrics.rebuild",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/feed/candidates",
            "feed.candidates.list",
        ),
        route(
            HttpMethod::Put,
            "/backend/v3/api/news/feed/candidates",
            "feed.candidates.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/feed/candidates/{candidateId}",
            "feed.candidates.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/interests",
            "interests.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/interests/rebuild",
            "interests.rebuild",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/interests/{interestId}",
            "interests.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/search/suggestions",
            "search.suggestions.management.list",
        ),
        route(
            HttpMethod::Put,
            "/backend/v3/api/news/search/suggestions",
            "search.suggestions.update",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/search/suggestions/{suggestionId}",
            "search.suggestions.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/search/events",
            "search.events.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/search/projections/rebuild",
            "search.projections.rebuild",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/experiments",
            "experiments.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/experiments",
            "experiments.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/experiments/{experimentId}",
            "experiments.update",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/experiments/{experimentId}/archive",
            "experiments.archive",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/notification/subscriptions",
            "notification.subscriptions.management.list",
        ),
        route(
            HttpMethod::Delete,
            "/backend/v3/api/news/notification/subscriptions/{subscriptionId}",
            "notification.subscriptions.delete",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/alerts/breaking",
            "alerts.breaking.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/alerts/breaking",
            "alerts.breaking.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/alerts/breaking/{alertId}",
            "alerts.breaking.update",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/alerts/breaking/{alertId}/publish",
            "alerts.breaking.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/alerts/breaking/{alertId}/cancel",
            "alerts.breaking.cancel",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/digests",
            "digests.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/digests",
            "digests.create",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/digests/{digestId}/publish",
            "digests.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/digests/{digestId}/items",
            "digests.items.create",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/trust/sources",
            "trust.sources.management.list",
        ),
        route(
            HttpMethod::Put,
            "/backend/v3/api/news/trust/sources",
            "trust.sources.update",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/trust/items/{itemId}",
            "trust.items.retrieve",
        ),
        route(
            HttpMethod::Put,
            "/backend/v3/api/news/trust/items/{itemId}",
            "trust.items.update",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/fact_checks",
            "factChecks.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/fact_checks",
            "factChecks.create",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/fact_checks/{factCheckId}/publish",
            "factChecks.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/fact_checks/{factCheckId}/archive",
            "factChecks.archive",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/corrections",
            "corrections.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/corrections",
            "corrections.create",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/corrections/{correctionId}/publish",
            "corrections.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/corrections/{correctionId}/archive",
            "corrections.archive",
        ),
        route(
            HttpMethod::Get,
            "/backend/v3/api/news/live/events",
            "live.events.management.list",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/live/events",
            "live.events.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/live/events/{eventId}",
            "live.events.update",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/live/events/{eventId}/publish",
            "live.events.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/live/events/{eventId}/close",
            "live.events.close",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/live/events/{eventId}/updates",
            "live.updates.create",
        ),
        route(
            HttpMethod::Patch,
            "/backend/v3/api/news/live/events/{eventId}/updates/{updateId}",
            "live.updates.update",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/live/events/{eventId}/updates/{updateId}/publish",
            "live.updates.publish",
        ),
        route(
            HttpMethod::Post,
            "/backend/v3/api/news/live/events/{eventId}/items",
            "live.items.create",
        ),
    ]
}

pub fn gateway_route_manifest() -> sdkwork_web_core::HttpRouteManifest {
    let routes = backend_routes()
        .into_iter()
        .map(|route| {
            sdkwork_web_core::HttpRoute::dual_token(
                framework_method(route.method),
                route.path,
                route.tag,
                route.operation_id,
            )
        })
        .collect();
    sdkwork_web_core::HttpRouteManifest::from_owned_routes(routes)
}

fn framework_method(method: HttpMethod) -> sdkwork_web_core::HttpMethod {
    match method {
        HttpMethod::Delete => sdkwork_web_core::HttpMethod::Delete,
        HttpMethod::Get => sdkwork_web_core::HttpMethod::Get,
        HttpMethod::Patch => sdkwork_web_core::HttpMethod::Patch,
        HttpMethod::Post => sdkwork_web_core::HttpMethod::Post,
        HttpMethod::Put => sdkwork_web_core::HttpMethod::Put,
    }
}

fn route(method: HttpMethod, path: &'static str, operation_id: &'static str) -> NewsHttpRoute {
    NewsHttpRoute::new(method, path, "news", operation_id)
}

pub fn gateway_mount(
    state: std::sync::Arc<sdkwork_routes_news_open_api::state::NewsHttpState>,
) -> axum::Router {
    routes::gateway_mount(state)
}
