import { useState } from "react";import { ArrowUpRight, Boxes, CheckCircle2, Download, PlugZap, Search, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react";import "./styles.css";
const tabs=[{id:"product",label:"AI 产品",icon:Boxes},{id:"skill",label:"Skills",icon:Wrench},{id:"mcp",label:"MCP 连接器",icon:PlugZap}];
const items=[
 {id:"deep-research",type:"product",name:"Deep Research",publisher:"SDKWork Labs",description:"跨来源深度研究、证据核验与结构化报告。",icon:"DR",color:"#16634f",rating:"4.9",users:"12.4k",verified:true},
 {id:"financial-reader",type:"skill",name:"Financial Reader",publisher:"SDKWork",description:"阅读财报、公告与电话会，提取指标变化和风险。",icon:"FR",color:"#2f638e",rating:"4.8",users:"8.7k",verified:true},
 {id:"policy-tracker",type:"skill",name:"Policy Tracker",publisher:"Open Policy",description:"持续跟踪法规政策并生成义务与生效时间线。",icon:"PT",color:"#83553e",rating:"4.7",users:"5.2k",verified:true},
 {id:"notion-mcp",type:"mcp",name:"Notion MCP",publisher:"Notion",description:"让助手读取和更新团队知识库中的授权页面。",icon:"N",color:"#252525",rating:"4.9",users:"24.8k",verified:true},
 {id:"github-mcp",type:"mcp",name:"GitHub MCP",publisher:"GitHub",description:"检索仓库、Issue、Pull Request 与发布记录。",icon:"GH",color:"#3b4248",rating:"4.9",users:"31.6k",verified:true},
 {id:"data-brief",type:"product",name:"Data Brief",publisher:"Northstar AI",description:"把业务数据变化自动转成每日管理简报。",icon:"DB",color:"#75558f",rating:"4.6",users:"3.1k",verified:false}
];
export function NewsPcAiStore(){const [tab,setTab]=useState("product");const [installed,setInstalled]=useState(new Set(["financial-reader"]));return <div className="news-ai-store"><header><div><h1>AI Store</h1><p>发现可组合的 AI 产品、Skills 与 MCP 连接器</p></div><label><Search size={17}/><input placeholder="搜索产品、能力或连接器"/></label></header><nav>{tabs.map(({id,label,icon:Icon})=><button className={id===tab?"is-active":""} onClick={()=>setTab(id)} key={id} type="button"><Icon size={16}/>{label}</button>)}</nav><main><section className="news-store-feature"><div><span><Sparkles size={14}/> 编辑精选</span><h2>构建你的新闻情报工作台</h2><p>把研究、知识库和业务系统连接到阅读助手，让每条重要变化直接进入工作流。</p><button type="button">查看组合方案 <ArrowUpRight size={15}/></button></div><div className="news-store-feature__stack"><span>Skill</span><span>Agent</span><span>MCP</span></div></section><div className="news-store-heading"><div><h2>{tabs.find(item=>item.id===tab)?.label}</h2><p>按可信度、使用量和近期质量综合排序</p></div><button type="button">全部分类</button></div><section className="news-store-grid">{items.filter(item=>item.type===tab).map(item=><article key={item.id}><header><span style={{background:item.color}}>{item.icon}</span><button type="button" title="详情"><ArrowUpRight size={16}/></button></header><h3>{item.name}{item.verified&&<ShieldCheck size={15}/>}</h3><small>{item.publisher}</small><p>{item.description}</p><div><span><Star size={13} fill="currentColor"/>{item.rating}</span><span><Download size={13}/>{item.users}</span></div><footer><button className={installed.has(item.id)?"is-installed":""} onClick={()=>setInstalled(current=>{const next=new Set(current);next.has(item.id)?next.delete(item.id):next.add(item.id);return next})} type="button">{installed.has(item.id)?<><CheckCircle2 size={14}/>已安装</>:"安装"}</button></footer></article>)}</section></main></div>}
export default NewsPcAiStore;
